apiVersion: v1
kind: Service
metadata:
  name: takeon-ui-test
  labels:
    run: takeon-ui-test
spec:
  ports:
  - port: 5000
    protocol: TCP
  selector:
    run: takeon-ui-test
  type: LoadBalancer

