apiVersion: apps/v1
kind: Deployment
metadata:
  name: takeon-ui-test
spec:
  selector:
    matchLabels:
      run: takeon-ui-test
  replicas: 3
  template:
    metadata:
      labels:
        run: takeon-ui-test
    spec:
      containers:
      - name: takeon-ui-test
        image: 014669633018.dkr.ecr.eu-west-2.amazonaws.com/takeon-ui-test
        ports:
        - containerPort: 5000

